### ISSUE TITLE
not all eras are from first January to end of December

### ISSUE THREAD

**Issue by dragouf** [KevinAdu/nengo#2]
Some lib result are wrong because all eras are not from january to december.  I forked your repository to return a more accurate result. here it is: https://github.com/dragouf/nengo

**Comment by KevinAdu** [comment]
Hey @dragouf 
Thank for logging the issue.

Yes you're correct, they are since they all start on specific date. If the month is going to be added, I think the day should also be added so it can 100% accurate.

For now, why don't you make a pull request so we can get the month implementation reviewed and merged?

I will create another issue to address the specific day as well.

**Comment by KevinAdu** [comment]
This has been fixed by merging your fork. (#6) Thanks.
